name: "GAP"
on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    # Every day at 3:15 AM UTC
    - cron: '15 3 * * *'

jobs:
  test:
    name: "${{ matrix.gap-branch }} / ${{ matrix.os }} / ${{ matrix.ABI }}-bit"
    runs-on: "${{ matrix.os }}-latest"
    # Don't run this twice for PRs from branches in the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        gap-branch:
          - stable-4.11
        ABI:
          - 64
          - 32

        include:
          # GAP stable-4.10
          - gap-branch: stable-4.10
            pkgs-to-clone: "datastructures images"
            os: ubuntu
            ABI: 64
          # macOS job
          - gap-branch: stable-4.11
            # to ensure datastructures>= v0.2.6
            pkgs-to-clone: "datastructures"
            os: macos
            ABI: 64

    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        if: ${{ runner.os == 'macOS' }}
        run: brew install automake
      # Setup ccache, to speed up repeated compilation of the same binaries
      # (i.e., GAP and the packages)
      - name: "Setup ccache"
        if: ${{ runner.os != 'Windows' }}
        uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          override_cache_key: ${{ runner.os }}-${{ matrix.gap-branch }}-${{ matrix.ABI }}-${{ github.ref }}
          override_cache_key_fallback: ${{ runner.os }}-${{ matrix.gap-branch }}-${{ matrix.ABI }}
      - name: "Install GAP and clone/compile necessary packages"
        uses: gap-actions/setup-gap@v2
        env:
          # We don't understand why this is necessary. Hopefully it can be
          # removed in the fullness of time.
          LDFLAGS: "-pthread"
        with:
          # digraphs included here to ensure version >=1.5.0
          GAP_PKGS_TO_CLONE: "digraphs/digraphs ${{ matrix.pkgs-to-clone }}"
          GAP_PKGS_TO_BUILD: "digraphs io orb datastructures profiling"
          GAPBRANCH: ${{ matrix.gap-branch }}
          ABI: ${{ matrix.ABI }}
      - name: "Build Semigroups"
        uses: gap-actions/build-pkg@v1
        with:
          ABI: ${{ matrix.ABI }}
          CONFIGFLAGS: --disable-hpcombi
      - name: "Run tst/teststandard.g"
        uses: gap-actions/run-pkg-tests@v2
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v2
